config/routes.rb
Rails.application.routes.draw do
  resources :season_stats
  resources :player_ratings
  get 'reports' => 'reports#index', as: :report_index
  get 'reports/leaderboard' => 'reports#leaderboard', as: :report_leaderboard
  get 'reports/player/:player_id' => 'reports#player', as: :player_report
  get 'reports/gameHistory/:game_id' => 'reports#game', as: :game_report
  get 'reports/historyTable/:player_id_1(/:player_id_2)' => 'reports#history', as: :history_table

  get 'players/:player_id/change_pin' => 'players#change_player_pin', as: :change_player_pin
  post 'players/:player_id/change_pin' => 'players#change_player_pin_post', as: :change_player_pin_post

  resources :rooms do
      resources :seasons do
        get 'leaderboard' => 'seasons#leaderboard', as: :leaderboard
      end
      get 'controller' => 'rooms#controller'
      get 'leaderboard' => 'rooms#leaderboard', as: :leaderboard
      get 'game/interstitial' => 'rooms#interstitial', as: :game_interstitial
      get 'game/new' => 'rooms#game_new', as: :game_new
      post 'game/new' => 'rooms#game_new_post', as: :game_new_post
      get 'game/' => 'rooms#game_view', as: :game_view
      get 'game/play' => 'rooms#game_play', as: :game_play
      post 'game/end' => 'rooms#game_end_post', as: :game_end
      get 'game/newfull' => 'rooms#game_newfull', as: :game_newfull
      post 'game/player_count' => 'rooms#game_player_count_post', as: :game_player_count_post
      get 'game/lookup_player' => 'players#lookup_player', as: :game_lookup_player
      get 'game/login_as/:player_id' => 'players#login_as_player', as: :game_login_as_player
      post 'game/login_as/:player_id' => 'players#login_as_player_post', as: :game_login_as_player_post

      post 'game/new/players/clear' => 'rooms#players_clear_post', as: :game_players_clear_post
      get 'game/new/players/create' => 'players#new', as: :game_new_player
      get 'game/new/players/create/cancel' => 'players#new_cancel', as: :game_new_player_cancel
      post 'game/new/players/create' => 'players#new_post', as: :game_new_player_post
      get 'game/new/players/:player_id' => 'players#confirm', as: :game_player_confirm
      delete 'game/new/players/:player_id' => 'players#delete', as: :game_player_delete
      get 'game/new/players/:player_id/attach_image' => 'players#attach_image', as: :game_player_attach_image
      post 'game/new/players/:player_id/attach_image' => 'players#attach_image_post', as: :game_player_attach_image_post
  end

  root 'rooms#home'
  
  get '/api/rooms/:id/end' => 'rooms#end_game'
  get '/api/rooms/:id/team/:team/increment/:request_id' => 'rooms#increment_score', as: :increment_score
  get '/api/rooms/:id/team/:team/decrement/:request_id' => 'rooms#decrement_score', as: :decrement_score
  get '/api/rooms/:id/team/:team/taunt/:request_id' => 'rooms#taunt', as: :taunt
  get '/api/rooms/:id/status' => 'rooms#room_status', as: :room_status
  get '/api/rooms/:room_id/players/add' => 'players#handle_player_hash', as: :handle_player_hash
  get '/api/rooms/:room_id/players/predict' => 'players#predict_game', as: :predict_game
  get '/api/rooms/:room_id/players/optimize' => 'players#optimize_teams', as: :optimize_teams
  get '/api/rooms/:room_id/players/rank' => 'players#get_rank', as: :get_player_rank
  get '/api/rooms/:room_id/send_current_scores' => 'rooms#send_current_scores'
  get '/api/rooms/:id/activeseason' => 'rooms#active_season'
  get '/api/players' => 'players#list_all_players'

  resources :bathrooms do
    get 'stalls/:stall_id/:state' => 'bathrooms#set_stall_status'
    get 'stalls_stats/:days_ago' => 'bathrooms#stats', as: :stall_stats
  end
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :room
  before_save :clear_active
  def clear_active
    if self.active == true
      room.seasons.update_all(active: false)
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy, :leaderboard]
  before_action :set_room

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = @room.seasons
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to room_seasons_url, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to [@room, @season], notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to room_seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def leaderboard
    season_id = @season.id
    ignore_deviation = params.key? :ignore_deviation
    if params.key? :game_type
      game_type = params[:game_type].to_i
    end
    if game_type != 1
      game_type = 2
    end
    if ignore_deviation
      @allPlayerRatings = PlayerDao::get_leaderboard_player_ratings(season_id, game_type, RatingManager::TRUESKILL_SIGMA, 500)
    else
      @allPlayerRatings = PlayerDao::get_leaderboard_player_ratings(season_id, game_type, PlayerDao::LEADERBOARD_DEVIATION_CUTOFF, 50)
    end
    @player_ratings = []
    @allPlayerRatings.each do |player_rating|
      if ignore_deviation || player_rating.deviation < PlayerDao::LEADERBOARD_DEVIATION_CUTOFF
        @player_ratings << player_rating
      end
    end
    @player_ratings
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id]) rescue Season.find(params[:season_id])
    end

    def set_room
      @room = Room.find(params[:room_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      var = params.require(:season).permit(:name, :active)
      var[:room_id] = @room.id
      var
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.haml
= form_for [@room, @season] do |f|
  - if @season.errors.any?
    #error_explanation
      %h2.font-white= "#{pluralize(@season.errors.count, "error")} prohibited this season from being saved:"
      %ul
        - @season.errors.full_messages.each do |msg|
          %li.font-white= msg

  .field
    = f.label :name, class: "font-white street-fighter"
    = f.text_field :name
  .field
    = f.label :active, class: "font-white street-fighter"
    = f.check_box :active, checked: true
  .actions
    = f.submit 'Save'

app/views/seasons/edit.html.haml
%h1 Editing season

= render 'form'

= link_to 'Show', room_season_url(@room, @season)
\|
= link_to 'Back', room_seasons_path

app/views/seasons/index.html.haml
%div.row
  %div.column.small-12
    %h1.street-fighter.sublabel.text-center
      Seasons
    = link_to 'New Season', new_room_season_path, class: "street-fighter font-white float-right"
%div.row
  %div.column.small-9.small-centered
    %table
      %thead
        %tr
          %td
            %h4.street-fighter
              \#
          %td
            %h4.street-fighter
              Name
          %td
            %h4.street-fighter
              Active
      %tbody
        - count = @seasons.count
        - @seasons.reverse.each_with_index do |season, index|
          %tr{"data-href": room_season_leaderboard_path(@room, season)}
            %td
              =link_to room_season_leaderboard_path(@room, season) do
                %h5.street-fighter
                  = @seasons.count - index
            %td
              =link_to room_season_leaderboard_path(@room, season) do
                %h5.street-fighter
                  = season.name
            %td
              =link_to room_season_leaderboard_path(@room, season) do
                %h5.street-fighter
                  = season.active ? "<<<<<" : ""
:javascript
  $('*[data-href]').on("click",function(){
    window.location = $(this).data('href');
    return false;
  });
  $("td > a").on("click",function(e){
    e.stopPropagation();
  });

app/views/seasons/leaderboard.haml
%div.row
  %div.column.small-12
    %h1.street-fighter.sublabel.text-center
      Leaderboard
%div.row
  %div.column.small-9.small-centered
    %table
      %thead
        %tr
          %td
            %h4.street-fighter
              Rank
          %td
            %h4.street-fighter
              Player
          %td
            %h4.street-fighter
              Rating
          %td
            %h4.street-fighter
              Deviation
      %tbody
        - @player_ratings.each_with_index do |player_rating,index|
          - player = player_rating.player
          %tr
            %td
              %h5.street-fighter
                =index + 1
            %td
              %h5.street-fighter
                =link_to(player.name, "/reports/player/#{player.id}", {:class => 'link-label'})
            %td
              %h5.street-fighter
                =(player_rating.skill * 1000).floor
            %td
              %h5.street-fighter
                =player_rating.deviation

app/views/seasons/new.html.haml
%div.row
  %div.column.small-12
    %h1.street-fighter.sublabel.text-center
      New Season
    = render 'form'

    = link_to 'Back', room_seasons_path, class: "street-fighter font-white"

app/views/seasons/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @season.name
%p
  %b Room:
  = @season.room.id
%p
  %b Active:
  = @season.active

= link_to 'Edit', edit_room_season_path(@room, @season)
\|
= link_to 'Back', room_seasons_path