config/routes.rb
Rails.application.routes.draw do
  resources :season_stats
  resources :player_ratings
  get 'reports' => 'reports#index', as: :report_index
  get 'reports/leaderboard' => 'reports#leaderboard', as: :report_leaderboard
  get 'reports/player/:player_id' => 'reports#player', as: :player_report
  get 'reports/gameHistory/:game_id' => 'reports#game', as: :game_report
  get 'reports/historyTable/:player_id_1(/:player_id_2)' => 'reports#history', as: :history_table

  get 'players/:player_id/change_pin' => 'players#change_player_pin', as: :change_player_pin
  post 'players/:player_id/change_pin' => 'players#change_player_pin_post', as: :change_player_pin_post

  resources :rooms do
      resources :seasons do
        get 'leaderboard' => 'seasons#leaderboard', as: :leaderboard
      end
      get 'controller' => 'rooms#controller'
      get 'leaderboard' => 'rooms#leaderboard', as: :leaderboard
      get 'game/interstitial' => 'rooms#interstitial', as: :game_interstitial
      get 'game/new' => 'rooms#game_new', as: :game_new
      post 'game/new' => 'rooms#game_new_post', as: :game_new_post
      get 'game/' => 'rooms#game_view', as: :game_view
      get 'game/play' => 'rooms#game_play', as: :game_play
      post 'game/end' => 'rooms#game_end_post', as: :game_end
      get 'game/newfull' => 'rooms#game_newfull', as: :game_newfull
      post 'game/player_count' => 'rooms#game_player_count_post', as: :game_player_count_post
      get 'game/lookup_player' => 'players#lookup_player', as: :game_lookup_player
      get 'game/login_as/:player_id' => 'players#login_as_player', as: :game_login_as_player
      post 'game/login_as/:player_id' => 'players#login_as_player_post', as: :game_login_as_player_post

      post 'game/new/players/clear' => 'rooms#players_clear_post', as: :game_players_clear_post
      get 'game/new/players/create' => 'players#new', as: :game_new_player
      get 'game/new/players/create/cancel' => 'players#new_cancel', as: :game_new_player_cancel
      post 'game/new/players/create' => 'players#new_post', as: :game_new_player_post
      get 'game/new/players/:player_id' => 'players#confirm', as: :game_player_confirm
      delete 'game/new/players/:player_id' => 'players#delete', as: :game_player_delete
      get 'game/new/players/:player_id/attach_image' => 'players#attach_image', as: :game_player_attach_image
      post 'game/new/players/:player_id/attach_image' => 'players#attach_image_post', as: :game_player_attach_image_post
  end

  root 'rooms#home'
  
  get '/api/rooms/:id/end' => 'rooms#end_game'
  get '/api/rooms/:id/team/:team/increment/:request_id' => 'rooms#increment_score', as: :increment_score
  get '/api/rooms/:id/team/:team/decrement/:request_id' => 'rooms#decrement_score', as: :decrement_score
  get '/api/rooms/:id/team/:team/taunt/:request_id' => 'rooms#taunt', as: :taunt
  get '/api/rooms/:id/status' => 'rooms#room_status', as: :room_status
  get '/api/rooms/:room_id/players/add' => 'players#handle_player_hash', as: :handle_player_hash
  get '/api/rooms/:room_id/players/predict' => 'players#predict_game', as: :predict_game
  get '/api/rooms/:room_id/players/optimize' => 'players#optimize_teams', as: :optimize_teams
  get '/api/rooms/:room_id/players/rank' => 'players#get_rank', as: :get_player_rank
  get '/api/rooms/:room_id/send_current_scores' => 'rooms#send_current_scores'
  get '/api/rooms/:id/activeseason' => 'rooms#active_season'
  get '/api/players' => 'players#list_all_players'

  resources :bathrooms do
    get 'stalls/:stall_id/:state' => 'bathrooms#set_stall_status'
    get 'stalls_stats/:days_ago' => 'bathrooms#stats', as: :stall_stats
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :room_players
  has_many :daily_stats
  has_many :weekly_stats
  has_many :season_stats
  has_many :rooms, through: :room_players
  has_many :player_ratings

  def get_latest_rating room_id
    room = Room.find(room_id)
    get_season_rating room.get_active_season.id
  end

  def get_season_rating season_id
    season = Season.find(season_id)
    rating = player_ratings.where(season_id: season.id).first
    if (rating == nil)
      rating = player_ratings.create(season_id: season.id)
    end
    rating
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  TEAM_A_ID = 'a'
  TEAM_B_ID = 'b'
  TEAM_IDS = [TEAM_A_ID, TEAM_B_ID]

  before_action :set_player, only: [:new_post, :confirm, :delete, :attach_image, :attach_image_post]
  before_action :set_room_id, except: [:list_all_players, :change_player_pin, :change_player_pin_post]

  def handle_player_hash
    # @type [String]
    hash = params[:uidHash]
    # SHA256 should be 32 bytes, 64 hex characters
    raise("invalid hash") if hash.length != 64

    # Lookup or create a player record for this player
    player = Player.find_by rfid_hash: hash
    if player.nil?
      # If a player with this hash doesn't exist, create a new one
      player = Player.create(rfid_hash: hash)
      # Send a message to the client to redirect to the create page
      ::WebsocketRails[:"room#{@id}"].trigger 'user_scan_new', player.id
    else
      # Otherwise this player exists, so add them to this room's current players
      add_player_and_update_room(player)
    end

    render nothing: true
  end

  def new
    @name = ''
    if params[:player_id].nil?
      # Grab the latest player added that doesn't have a name, we'll edit them
      @player = Player.where(name: nil).last
      raise("No unregistered players found") if @player.nil?
    else
      # If we're adding/editing a specific player
      @player = Player.find_by id: params[:player_id]
      raise("Failed to find player for id #{params[:player_id]}") if @player.nil?
      @name = @player.name
    end

    add_new_player(@id, @player)
  end

  def new_cancel
    player = Player.where(name: nil).last
    remove_player_from_room_if_present(player)
    if player
      player.delete
    end
    redirect_to room_game_newfull_path
  end

  def new_post
    raise("Failed to find player for id #{params[:player_id]}") if @player.nil?
    @player.name = params[:name]
    if params[:pin]
      @player.pin = params[:pin]
    end
    @player.save
    redirect_to room_game_player_attach_image_path(room_id: @id, player_id: @player.id)
  end

  def attach_image
  end

  def attach_image_post
    unless params[:capture].nil?
      image = params[:capture][:image]
      hash = Cloudinary::Uploader.upload(image, cloudinary_auth)
      image_url = hash['secure_url']
      @player.update_attribute(:image_url, image_url)
    end
    redirect_to room_game_newfull_path
  end

  def confirm
  end

  def delete
  end

  def get_rank
    # @type [Array<Integer>]
    player_ids = params[:playerIds]
    unless player_ids
      render :json => nil
      return
    end
    player_ids.map! { |player_id| player_id.to_i }

    render :json => RankingHelper::get_player_rankings(player_ids)
  end

  def predict_game
    player_ids = params[:playerIdHash]
    room_id = params[:room_id]

    team_a = player_ids[:a].map { |player_id| Player.find(player_id).get_latest_rating(room_id) }
    team_b = player_ids[:b].map { |player_id| Player.find(player_id).get_latest_rating(room_id) }

    manager = ResultPredictionManager.new
    winning_team, winning_score = manager.predict_result(team_a, team_b)

    if winning_team == team_a
      favored_team = :a
    elsif winning_team == team_b
      favored_team = :b
    else
      raise "Failed to predict game, invalid winning team #{winning_team}"
    end

    # winning_ids = winning_team.map { |player| player.id }

    render :json => {
        favoredTeam: favored_team,
        pointSpread: winning_score
    }
  end

  def optimize_teams
    player_ids = params[:players].split(',')
    room_id = params[:room_id]
    season = Room.find(room_id).get_active_season
    player_ratings = player_ids.map { |player_id| Player.find(player_id).get_latest_rating(room_id) }

    manager = ResultPredictionManager.new
    team_1, team_2 = manager.optimize_teams(*player_ratings)

    # Client-side will clear all existing players, so add them back on the server side
    # and fire off websocket updates

    team_1.each do |player_rating|
      add_player_and_update_room(player_rating.player)
    end
    team_2.each do |player_rating|
      add_player_and_update_room(player_rating.player)
    end

    playerIdHash = {
        a: team_1.map { |player_rating| player_rating.player.id },
        b: team_2.map { |player_rating| player_rating.player.id },
    }

    render :json => playerIdHash
  end

  def lookup_player
    @players = Player.where.not(name: nil).sort_by(&:name)

    # If we got here from the "already in the system?" link after scanning an
    # unrecognized badge, we want to pass the new-badge player through the process
    # so that we can update the chosen player's badge hash from the new-badge 
    # "empty" player entry, and then delete that "empty" entry.
    if params[:badged_player_id]
      @badged_player_id = params[:badged_player_id]
    end
  end

  def login_as_player
    player_id = params[:player_id]
    @player = Player.find(player_id)
    raise "No player found for id '#{player_id}'" unless @player

    # If we got here from the "already in the system?" link after scanning an
    # unrecognized badge, we want to pass the new-badge player through the process
    # so that we can update the chosen player's badge hash from the new-badge 
    # "empty" player entry, and then delete that "empty" entry.
    if params[:badged_player_id]
      @badged_player_id = params[:badged_player_id]
    end

    # If an error was passed to this page, show that error.
    if params[:error]
      @error = params[:error]
    end
  end
  def login_as_player_post
    player_id = params[:player_id]
    @player = Player.find(player_id)
    raise "No player found for id '#{player_id}'" unless @player

    pin = params[:pin]
    if pin && pin.strip == @player.pin
      add_player_and_update_room(@player)

      # If we got here from the "already in the system?" link after scanning an
      # unrecognized badge, we want to take the new badge's hash from the 
      # "empty" player entry that badged in, and apply it to the player that was
      # just selected (allowing players to update their badge), then delete 
      # "empty" player entry since it doesn't mean anything anymore.
      if params[:badged_player_id]
        update_player_badge(@player, params[:badged_player_id])
      end

      redirect_to room_game_newfull_path
    else
      redirect_to room_game_login_as_player_path(
        id: @id, 
        player_id: @player.id, 
        error: "Incorrect pin!", 
        badged_player_id: params[:badged_player_id]
      )
    end
  end

  def change_player_pin
    player_id = params[:player_id]
    @player = Player.find(player_id)
    raise "No player found for id '#{player_id}'" unless @player

    if params[:error]
      @error = params[:error]
    end
  end
  def change_player_pin_post
    player_id = params[:player_id]
    @player = Player.find(player_id)
    raise "No player found for id '#{player_id}'" unless @player

    new_pin = params[:new_pin]
    current_pin = params[:current_pin]
    if @player.pin != current_pin
      redirect_to change_player_pin_path(
        player_id: @player.id,
        error: "Incorrect pin!"
      )
    elsif !new_pin || new_pin.size < 3
      redirect_to change_player_pin_path(
        player_id: @player.id,
        error: "Invalid pin; your pin must be at least 3 digits long."
      )
    else
      @player.pin = new_pin
      @player.save
      redirect_to player_report_path(player_id: @player.id)
    end
  end

  # Used by the ajax player search
  def list_all_players
    json_output = Player.all.map do |player|
      {
        id: player.id,
        name: player.name,
        image_url: player.image_url,
      }
    end

    render :json => json_output
  end
  

  private

  # @param player [Player]
  def add_player_and_update_room(player)
    room_player = add_new_player(@id, player)
    ::WebsocketRails[:"room#{@id}"].trigger 'user_scan_existing', {
        :player_id => player.id,
        :image_url => player.image_url,
        :team => room_player.team,
        :player_number => room_player.player_number
    }
  end

  def add_new_player(room_id, player)
    # Pull the room object
    # @type [Room]
    room = Room.find_by id: room_id
    raise("Invalid room id #{room_id}") if room.nil?

    team_size = (room.player_count / 2).to_i
    # Grab the players for this room to find where to put this player
    room_players = room.room_players

    # If this player is already playing, we're done here
    self_players = room_players.select {|room_player| room_player.player_id == player.id}
    if self_players.length > 0
      return RoomPlayer.find_by player_id: player.id, room_id: room_id
    end

    # @type [Array<RoomPlayer>]
    team_a_players = room_players.select {|room_player| room_player.team == TEAM_A_ID}
    # @type [Array<RoomPlayer>]
    team_b_players = room_players.select {|room_player| room_player.team == TEAM_B_ID}

    # Add to team A first
    if team_a_players.length < team_size
      room_player = RoomPlayer.new(room_id: room_id, player_id: player.id, team: TEAM_A_ID, player_number: team_a_players.length + 1)
    elsif team_b_players.length < team_size
      # If team B isn't full, add to it
      room_player = RoomPlayer.new(room_id: room_id, player_id: player.id, team: TEAM_B_ID, player_number: team_b_players.length + 1)
    else
      # Failing that, add to the last player slot
      room_player = RoomPlayer.find_by room_id: room_id, team: TEAM_B_ID, player_number: team_size
      raise("Failed to find player number #{team_size} for team #{TEAM_B_ID} and room #{room_id} when trying to overwrite last player") if room_player.nil?
      room_player.player_id = player.id
    end

    room_player.save
    room_player
  end

  def set_player
    @player = Player.find(params[:player_id])
  end

  def set_room_id
    @id = Room.find(params[:room_id]).id
  end

  def update_player_badge(player_to_update, badged_player_id)
    badged_player = Player.find(badged_player_id)

app/helpers/players_helper.rb
module PlayersHelper
  def alphabet
    thing = (10...36).map{ |i| i.to_s 36 }
    thing += ['.', '+', '-', '_']
    thing += (1...10).map{ |i| i.to_s }
    thing += ['0']
    thing
  end

  def digits
    thing = (1..9).map {|i| i.to_s }
    thing += ['0']
  end
end

app/views/players/attach_image.haml
%script{:src => "/javascript/webcam.js"}
.title ADD player
%hr.players
=form_tag room_game_player_attach_image_post_path(player_id: @player.id, room_id: @id) do
  .row
    .columns.small-6
      #my_camera.center-vertical
      #results.center-vertical{style: "display:none; width: 320px; height: 240px;"}
    .columns.small-6
      .row.top.camera
        .center-vertical
          %input.take-snapshot.player-button.player-button-border{:onclick => "take_snapshot()", :type => "button", :value => "Take Snapshot"}
          %input.retake-snapshot.player-button.player-button-border{:onclick => "retake_snapshot()", :type => "button", :value => "Retake Snapshot", :style => "display:none"}
          .top-text
      .row.bottom.camera
        .center-vertical
          #timer
          =submit_tag "Okay!", class: 'submit-image center player-button player-button-border'


%hr.players

:javascript
  Webcam.set({
    width: 320,
    height: 240,
    image_format: 'jpeg',
    jpeg_quality: 90
  });
  Webcam.attach( '#my_camera' );
  function take_snapshot() {
    $(".take-snapshot").css({"display":"none"});
    $(".top-text").text("Say Cheese!");
    var counter = 0;
    var id;
    id = setInterval(function() {
        counter--;
        if(counter < 0) {
          $("#timer").text('');
          $(".top-text").text('');
          Webcam.snap( function(data_uri) {
          toggle_things();
          document.getElementById('results').innerHTML =
            '<img src="'+data_uri+'"/>' +
            "<input id=\"capture_image\" type=\"hidden\" value=\""+data_uri+"\" name=\"capture[image]\">";
          } );
          clearInterval(id);
        } else {
          $("#timer").text('[' + counter + ']');
        }
    }, 1000);
  }
  function retake_snapshot() {
    toggle_things();
    document.getElementById('results').innerHTML = '';
    take_snapshot();
  }
  function toggle_things() {
    $("#timer").toggle();
    $(".submit-image").toggle();
    $(".retake-snapshot").toggle();
    $('#my_camera').toggle();
    $('#results').toggle();
  }

app/views/players/change_player_pin.haml
=form_tag change_player_pin_post_path(id: @id, player_id: @player.id), class: 'change-player-pin' do
  - if @error
    %div.error
      #{@error}
  =image_tag @player.image_url, alt: @player.name, height: 200, width: 200, class: 'player-icon'
  %div.player-name 
    #{@player.name}
  =label_tag "current_pin", "Current PIN", class:"pin-entry-label"
  =password_field_tag "current_pin", nil, class:"pin-entry"
  =label_tag "new_pin", "New PIN", class:"pin-entry-label"
  =password_field_tag "new_pin", nil, class:"pin-entry"
  =submit_tag "OK!", class:"submit-pin-entry"
    

app/views/players/login_as_player.haml
=form_tag room_game_login_as_player_post_path(id: @id, player_id: @player.id, badged_player_id: @badged_player_id), class: 'login-as-player' do
  - if @error
    %div.error
      #{@error}
  =image_tag @player.image_url, alt: @player.name, height: 200, width: 200, class: 'player-icon'
  %div.player-name 
    #{@player.name}
  =label_tag "pin", "Enter PIN", class:"pin-entry-label"
  =password_field_tag "pin", nil, class:"pin-entry", autofocus: true
  =submit_tag "OK!", class:"submit-pin-entry"
    

app/views/players/lookup_player.haml
%div.player-select
  - @players.each do |player|
    =link_to room_game_login_as_player_path(id: @id, player_id: player.id, badged_player_id: @badged_player_id), class: "player" do
      =image_tag "#{player.image_url}", alt: "#{player.name}", height: '175', width: '175', class: 'player-icon'
      %div.player-name
        #{player.name}

app/views/players/new.haml
=form_tag room_game_new_player_post_path(id: @id, player_id: @player.id) do
  .title Name your player
  %hr.players
  .scoring#table
    .game-column#question-mark-square
      .square ?
    .game-column#name-input-section
      %div#block-inline
        =label_tag :name, "name:", class:"name-text"
        =text_field_tag :name, "", class: "player-name-text-input"
        .keyboard
          .characters
            -alphabet.each_with_index do |letter, i|
              -if i%10 == 0
                <br>
              =link_to letter, '#', class: 'keyboard-buttons character', onclick: "append_character('#{letter}')"
          .characters.delete-row
            =link_to "DEL", '#', class: 'keyboard-buttons delete', onclick: "remove_character()"
    .game-column#pin-input-section
      %div#block-inline
        =label_tag "pin", "pin:", class:"pin-text"
        =password_field_tag "pin", "", class: "player-pin-text-input"
        .keyboard
          .digits
            -digits.each_with_index do |digit, i|
              -if i%3 == 0
                <br>
              =link_to digit, '#', class: "keyboard-buttons digit #{digit == '0' ? 'zero' : ''}", onclick: "append_pin_digit('#{digit}')"
          .digits.delete-row
            =link_to "DEL", '#', class: 'keyboard-buttons delete', onclick: "remove_pin_digit()"
  %hr.players
  .submit-cancel-button-container
    =link_to room_game_new_player_cancel_path do
      =button_tag "CANCEL", type: "button", class: 'cancel-button'
    =link_to "NEW BADGE?", room_game_lookup_player_path(id: @id, badged_player_id: @player.id), class: 'new-badge-for-existing-player-button'
    =submit_tag "OK!", class: 'submit-button'

  :javascript
    function append_character(letter) {
      var current_input = $(".player-name-text-input").val();
      if (current_input.length < 12) {
        $(".player-name-text-input").val(  $(".player-name-text-input").val() + letter);
      }
    }

    function remove_character() {
        var inputValue = $(".player-name-text-input").val();
        $(".player-name-text-input").val(inputValue.substring(0, inputValue.length-1));
    }

    function append_pin_digit(digit) {
      var current_input = $(".player-name-text-input").val();
      if (current_input.length < 12) {
        $(".player-pin-text-input").val(  $(".player-pin-text-input").val() + digit);
      }
    }

    function remove_pin_digit() {
        var inputValue = $(".player-pin-text-input").val();
        $(".player-pin-text-input").val(inputValue.substring(0, inputValue.length-1));
    }

    window.onload = function() {
      document.getElementById("name").focus();
    };