config/routes.rb
Rails.application.routes.draw do
  resources :season_stats
  resources :player_ratings
  get 'reports' => 'reports#index', as: :report_index
  get 'reports/leaderboard' => 'reports#leaderboard', as: :report_leaderboard
  get 'reports/player/:player_id' => 'reports#player', as: :player_report
  get 'reports/gameHistory/:game_id' => 'reports#game', as: :game_report
  get 'reports/historyTable/:player_id_1(/:player_id_2)' => 'reports#history', as: :history_table

  get 'players/:player_id/change_pin' => 'players#change_player_pin', as: :change_player_pin
  post 'players/:player_id/change_pin' => 'players#change_player_pin_post', as: :change_player_pin_post

  resources :rooms do
      resources :seasons do
        get 'leaderboard' => 'seasons#leaderboard', as: :leaderboard
      end
      get 'controller' => 'rooms#controller'
      get 'leaderboard' => 'rooms#leaderboard', as: :leaderboard
      get 'game/interstitial' => 'rooms#interstitial', as: :game_interstitial
      get 'game/new' => 'rooms#game_new', as: :game_new
      post 'game/new' => 'rooms#game_new_post', as: :game_new_post
      get 'game/' => 'rooms#game_view', as: :game_view
      get 'game/play' => 'rooms#game_play', as: :game_play
      post 'game/end' => 'rooms#game_end_post', as: :game_end
      get 'game/newfull' => 'rooms#game_newfull', as: :game_newfull
      post 'game/player_count' => 'rooms#game_player_count_post', as: :game_player_count_post
      get 'game/lookup_player' => 'players#lookup_player', as: :game_lookup_player
      get 'game/login_as/:player_id' => 'players#login_as_player', as: :game_login_as_player
      post 'game/login_as/:player_id' => 'players#login_as_player_post', as: :game_login_as_player_post

      post 'game/new/players/clear' => 'rooms#players_clear_post', as: :game_players_clear_post
      get 'game/new/players/create' => 'players#new', as: :game_new_player
      get 'game/new/players/create/cancel' => 'players#new_cancel', as: :game_new_player_cancel
      post 'game/new/players/create' => 'players#new_post', as: :game_new_player_post
      get 'game/new/players/:player_id' => 'players#confirm', as: :game_player_confirm
      delete 'game/new/players/:player_id' => 'players#delete', as: :game_player_delete
      get 'game/new/players/:player_id/attach_image' => 'players#attach_image', as: :game_player_attach_image
      post 'game/new/players/:player_id/attach_image' => 'players#attach_image_post', as: :game_player_attach_image_post
  end

  root 'rooms#home'
  
  get '/api/rooms/:id/end' => 'rooms#end_game'
  get '/api/rooms/:id/team/:team/increment/:request_id' => 'rooms#increment_score', as: :increment_score
  get '/api/rooms/:id/team/:team/decrement/:request_id' => 'rooms#decrement_score', as: :decrement_score
  get '/api/rooms/:id/team/:team/taunt/:request_id' => 'rooms#taunt', as: :taunt
  get '/api/rooms/:id/status' => 'rooms#room_status', as: :room_status
  get '/api/rooms/:room_id/players/add' => 'players#handle_player_hash', as: :handle_player_hash
  get '/api/rooms/:room_id/players/predict' => 'players#predict_game', as: :predict_game
  get '/api/rooms/:room_id/players/optimize' => 'players#optimize_teams', as: :optimize_teams
  get '/api/rooms/:room_id/players/rank' => 'players#get_rank', as: :get_player_rank
  get '/api/rooms/:room_id/send_current_scores' => 'rooms#send_current_scores'
  get '/api/rooms/:id/activeseason' => 'rooms#active_season'
  get '/api/players' => 'players#list_all_players'

  resources :bathrooms do
    get 'stalls/:stall_id/:state' => 'bathrooms#set_stall_status'
    get 'stalls_stats/:days_ago' => 'bathrooms#stats', as: :stall_stats
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :room_players, dependent: :destroy
  has_many :players, through: :room_players
  has_many :seasons, dependent: :destroy

  NO_TEAM_SERVING = 0
  TEAM_A_SERVING = 1
  TEAM_B_SERVING = 2

  # @param quit [boolean]
  def end_game(quit)
    if memorable_game?
      save_history(self)
    end
    update_attributes(team_a_score: 0, team_b_score: 0, streak: 0, streak_history: "")
    if quit
      room_players.delete_all
      update_attributes(game_session_id: nil, game: false)
    else
      update_attributes(team_a_score: 0, team_b_score: 0, game: true, start_time: Time.now)
      room_players.each do |room_player|
        if room_player.team == "a"
          room_player.update_attribute(:team, "b")
        elsif room_player.team == "b"
          room_player.update_attribute(:team, "a")
        end
      end

    end
  end

  def memorable_game?
    room_players.length > 0 &&
    # Should be an even number of players
        room_players.length % 2 === 0 &&
        room_players.length == player_count &&
    # Somebody should have won the game
        (team_a_score > GameLogic::PENULTIMATE_SCORE || team_b_score > GameLogic::PENULTIMATE_SCORE) &&
        !game_session_id.nil?
  end

  def save_history(room)
    # @type [Array<RoomPlayer>]
    team_a_player_ratings = room_players.select {|room_player| room_player.team == PlayersController::TEAM_A_ID}
    # @type [Array<RoomPlayer>]
    team_b_player_ratings = room_players.select {|room_player| room_player.team == PlayersController::TEAM_B_ID}

    # We should batch this but ActiveRecord makes it a pain in the ass and I don't care that much
    # @type [Hash{Integer => GameHistory}]
    histories = {}
    # @type [Array<PlayerRating>]
    winning_player_ratings = []
    # @type [Array<PlayerRating>]
    losing_player_ratings = []
    if team_a_score > team_b_score
      # Yay for team A
      team_a_player_ratings.each do |room_player|
        history = new_game_history(room, room_player, true)
        histories[room_player.player_id] = history
        winning_player_ratings << get_player_rating(room_player, room)
      end
      team_b_player_ratings.each do |room_player|
        history = new_game_history(room, room_player, false)
        histories[room_player.player_id] = history
        losing_player_ratings << get_player_rating(room_player, room)
      end
    else
      team_a_player_ratings.each do |room_player|
        history = new_game_history(room, room_player, false)
        histories[room_player.player_id] = history
        losing_player_ratings << get_player_rating(room_player, room)
      end
      # All glory to team B
      team_b_player_ratings.each do |room_player|
        history = new_game_history(room, room_player, true)
        histories[room_player.player_id] = history
        winning_player_ratings << get_player_rating(room_player, room)
      end
    end

    # Use the first player's history PK as the game ID because it's an easy way to generate a unique, sequential integer
    game_id = histories.values[0].id
    histories.each do |player_id, history|
      history.update_attributes(game_id: game_id)
    end

    starting_skills = {}
    starting_deviations = {}

    # Store starting ratings so we can calculate differential
    player_ratings = winning_player_ratings + losing_player_ratings
    player_ratings.each do |player_rating|
      starting_skills[player_rating.player_id] = player_rating.skill
      starting_deviations[player_rating.player_id] = player_rating.deviation
    end

    # Update skills
    margin = (team_a_score - team_b_score).abs
    manager = RatingManager.new
    manager.process_game(winning_player_ratings, margin, losing_player_ratings, -margin)
    winning_player_ratings.each { |player_rating| player_rating.save }
    losing_player_ratings.each { |player_rating| player_rating.save }

    # Calculate and store rating differentials
    # @type player [Player]
    player_ratings.each do |player_rating|
      # @type [GameHistory]
      player_history = histories[player_rating.player_id]
      player_history.skill_change = player_rating.skill - starting_skills[player_rating.player_id]
      player_history.deviation_change = player_rating.deviation - starting_deviations[player_rating.player_id]
      player_history.save
    end

    # Store score history for the game
    streak_histories = streak_history.split(",").map(&:to_i)
    streak_histories.each{ |streak_element|
      team = "a"
      score_change = 1
      if streak_element < 0
        team = "b"
        score_change = -1
      end
      # @type [ScoreHistory]
      score_history = ScoreHistory.new(
         game_id: game_id,
         team: team,
         created_at: Time.now,
      )
      score_history.save
      score_history
    }
  end

  def get_player_rating(room_player, room)
    active_season_id = room.get_active_season.id
    game_type = room.player_count / 2 # 1: singles, 2: doubles
    player = Player.find_by(:id => room_player.player_id)
    player_rating = player.player_ratings.where(:season_id => active_season_id).where(:game_type => game_type).first
    if player_rating == nil
      player_rating = PlayerRating.new(
        player_id: player.id,
        season_id: active_season_id,
        game_type: game_type,
        skill: RatingManager::TRUESKILL_MU,
        deviation: RatingManager::TRUESKILL_SIGMA
      )
      player_rating.save
    end

    return player_rating
  end

  # @param room_player [RoomPlayer]
  # @param win [boolean]
  # @return [GameHistory]
  def new_game_history(room, room_player, win)
    game_history = GameHistory.new(
        room_id: room.id,
        player_id: room_player.player_id,
        game_session_id: room.game_session_id,
        player_count: room.player_count,
        win: win,
        duration_seconds: (Time.now - room.start_time).to_i
    )
    if room_player.team == PlayersController::TEAM_A_ID
      game_history.player_team_score = room.team_a_score
      game_history.opponent_team_score = room.team_b_score
    else
      game_history.player_team_score = room.team_b_score
      game_history.opponent_team_score = room.team_a_score
    end
    game_history.save
    game_history
  end

  def handle_request_id (request_id)
    if request_id == 0 || last_request_id == nil
      #Request Id has been reset to 0. Likely the client has power cycled
        update_attribute(:last_request_id, 0)
        return true
    end

    if request_id > last_request_id
      update_attribute(:last_request_id, request_id)
      return true
    end
    return false
  end

  # @param increment_or_decrement boolean
  # @param team String
  def update_streak(room, increment_or_decrement, team)
    if increment_or_decrement
      new_streak = StreakHelper.new().update_streak_increment(team, get_streak_history(room.streak_history))
    else
      new_streak = StreakHelper.new().update_streak_decrement(team, get_streak_history(room.streak_history))
    end
    update_attribute(:streak, StreakHelper.new().get_new_streak(new_streak))
    update_attribute(:streak_history, new_streak.join(","))
  end

  #@return [int]
  def get_streak_history(streak_history)
    if streak_history == nil
      return []
    else
      return streak_history.split(",").map(&:to_i)
    end
  end

  def get_active_season
    return seasons.where(:active => true).first
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def get_team_a_name(player_rankings)
    a_room_players = @room.room_players.select {|room_player| room_player.team == PlayersController::TEAM_A_ID}
    team_a_players = []
    for room_player in a_room_players
      team_a_players << (@room.players.select {|player| player.id == room_player.player_id})[0]
    end

    if team_a_players.length > 0
      names = []
      team_a_players.each do |player|
        if player_rankings.has_key?(player.id)
          names << "#{player.name} (\##{player_rankings[player.id]})"
        else
          names << player.name
        end
      end
      name = names.join(' // ')
    else
      name = "Chatty"
    end
    name
  end

  def team_b_name(player_rankings)
    b_room_players = @room.room_players.select {|room_player| room_player.team == PlayersController::TEAM_B_ID}
    team_b_players = []
    for room_player in b_room_players
      team_b_players << (@room.players.select {|player| player.id == room_player.player_id})[0]
    end

    if team_b_players.length > 0
      names = []
      team_b_players.each do |player|
        if player_rankings.has_key?(player.id)
          names << "#{player.name} (\##{player_rankings[player.id]})"
        else
          names << player.name
        end
      end
      name = names.join(' // ')
    else
      name = "Sassy"
    end

    name
  end

end

app/views/rooms/_form.html.haml
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      %h2= "#{pluralize(@room.errors.count, "error")} prohibited this room from being saved:"
      %ul
        - @room.errors.full_messages.each do |msg|
          %li= msg

  .field
    eventually this will be generated
    = f.label :client_token
    = f.text_field :client_token
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/rooms/_match_screen.haml
- @audio_filenames.each do |filename, path|
  %audio{:id => filename, :style => "display: none;", :src => '/' + path}
%p
  #room-id= @room.id
.scoring
  .game-column.center#left
    .progress
      .meter#a_meter &nbsp;
    .name-container
      %h3.sf#team_a_name= get_team_a_name(@player_rankings)
    %h2.sf.team-status#team_a_status
    %h1.sf.team-score#team_a_score.center= @team_a_score
  .game-column.center#middle
    %h3.sf vs
    .predictions
      .prediction-container.left.view-game
        %img#team_a_star{:style => "display: none;", :src => "/images/pong_assets/favstar.gif"}
        %p.prediction-text#team_a_favored.sf
      .prediction-container.right.view-game
        %img#team_b_star{:style => "display: none;", :src => "/images/pong_assets/favstar.gif"}
        %p.prediction-text#team_b_favored.sf
  .game-column.center#right
    .progress
      .meter#b_meter &nbsp;
    .name-container
      %h3.sf#team_b_name= team_b_name(@player_rankings)
    %h2.sf.team-status#team_b_status
    %h1.sf.team-score#team_b_score.center= @team_b_score
:javascript
  let pageType = 'view_game';
  let playerIdHash = JSON.parse('#{@player_ids}');
  let playerCount = #{@room.player_count};

app/views/rooms/controller.haml
.button{onclick: 'Increment("a")'} Increment A
.button{onclick: 'Increment("b")'} Increment B
.send-badge
  .columns.small-2
    .button{onclick: 'SendBadge()'} Send Badge:
  .columns.small-2.end
    %input#badge-input{type: "text"}

:javascript
  function Increment(team) {
    $.get("/api/rooms/#{@room.id}/team/" + team + "/increment", function() {});
  }
  function SendBadge() {
    var badgeString = $("#badge-input").val();
    var length = badgeString.length;
    for (var i = length; i < 64; i++) {
      badgeString += "a";
    }
    console.log(length);
    console.log(badgeString);
    $.get("/api/rooms/#{@room.id}/players/add?uidHash=" + badgeString);
  }

app/views/rooms/decrement_score.haml
{}

app/views/rooms/edit.html.haml
%h1 Editing room

= render 'form'

= link_to 'Show', @room
\|
= link_to 'Back', rooms_path

app/views/rooms/game_new.haml
#room-id=@id
.center{:style => "position: relative; top: 75%;"}
  =form_tag room_game_new_post_path(id: @id) do
    =submit_tag "START QUICK GAME", class: "sf sf-button quick-game center transparent-bg"

app/views/rooms/game_newfull.haml
#room-id=@id
-avatar_container_box_height='100%'
-player_box_padding='0%'
-default_team_a_avatar='/images/pong_assets/pong_avatar 1 doubles.png'
-default_team_b_avatar='/images/pong_assets/pong_avatar 2 doubles.png'
.center{:style => "position: relative; top: 1%; text-align: center"}

%div{:style => "bottom: 0%; width: 100%; position: absolute; height: 50%; display:flex; justify-content: space-between; padding: 1%;"}
  .left-container{:style => "height: 100%; width: 33%; padding: #{player_box_padding};"}
    .avatar-container{:style => "height: #{avatar_container_box_height}; width: 100%"}
      -#Doubles#
      .picturebox.doubles-picturebox.doubles-player-1.left{:style => "display: none;"}
        %img.player_a_1_img{:src => @player_a_1_url, :style => "height: 100%; width: 100%;"}
        %p.player-ranking.left.player_a_1_ranking.street-fighter
      .picturebox.doubles-picturebox.doubles-player-2.left{:style => "display: none;"}
        %img.player_a_2_img{:src => @player_a_2_url, :style => "height: 100%; width: 100%;"}
        %p.player-ranking.left.player_a_2_ranking.street-fighter
      -#Singles#
      .picturebox.singles-picturebox.left{:style => "display: none;"}
        %img.player_a_1_img{:src => @player_a_1_url, :style => "height: 100%; width: 100%;"}
        %p.player-ranking.left.player_a_1_ranking.street-fighter
      .prediction-container.left.new-game
        %p.prediction-text#team_a_favored.street-fighter
        %img#team_a_star{:style => "display: none;", :src => "/images/pong_assets/favstar.gif"}

  .middle-container{:style => "height: 100%; width: 33%; padding: 2%;"}

    .column.settingsbox{:style => "height: 100%; width: 100%; text-align:center;"}
      %h4.sf Select Play Mode:
      .column.gametype{:style => "position: relative; margin: auto; display: flex; top: 1%;"}
        .sf-button.hoverable#singlesButton{:style => "width: 185px; height: 60px; margin: 20px auto; background-size: 100% 100%;"}
          .sf-label.hoverable SINGLES
        .sf-button.hoverable#doublesButton{:style => "width: 185px; height: 60px; margin: 20px auto; background-size: 100% 100%;"}
          .sf-label.hoverable DOUBLES

      #scan_section{:style => "padding: 2%;"}
        .sf-button#scanButton{:style => "margin: 10px auto; background-size: 100% 100%"}
          .sf-label#scanLabel SCAN PLAYER

        =link_to room_game_lookup_player_path(id: @id), :class => 'sf-button hoverable', :style => 'margin: 10px auto' do
          .sf-label.hoverable#lookupPlayerLabel LOOKUP PLAYER

        .sf-button.hoverable#clearButton{:style => "margin: 10px auto; background-size: 100% 100%;"}
          .sf-label.hoverable CLEAR PLAYERS
        =form_tag room_game_new_post_path(id: @id), :style => 'margin: 10px auto' do
          =submit_tag '* START GAME *', id: 'startButton', class: 'sf-button sf-label hoverable', style: "margin: 0 auto; display: inline-block; background-size: 100% 100%"


  .right-container{:style => "height: 100%; width: 33%; padding: #{player_box_padding};"}
    .avatar-container{:style => "height: #{avatar_container_box_height}; width: 100%"}
      -#Doubles#
      .picturebox.doubles-picturebox.doubles-player-1.right{:style => "display: none;"}
        %img.player_b_1_img{:src => @player_b_1_url, :style => "height: 100%; width: 100%;"}
        %p.player-ranking.right.player_b_1_ranking.street-fighter
      .picturebox.doubles-picturebox.doubles-player-2.right{:style => "display: none;"}
        %img.player_b_2_img{:src => @player_b_2_url, :style => "height: 100%; width: 100%;"}
        %p.player-ranking.right.player_b_2_ranking.street-fighter
      -#Singles#
      .picturebox.singles-picturebox.right{:style => "display: none;"}
        %img.player_b_1_img{:src => @player_b_1_url, :style => "height: 100%; width: 100%;"}
        %p.player-ranking.right.player_b_1_ranking.street-fighter
      .prediction-container.right.new-game
        %img#team_b_star{:style => "display: none;", :src => "/images/pong_assets/favstar.gif"}
        %p.prediction-text#team_b_favored.street-fighter
:javascript
  let playerCount = #{@player_count};
  let playerIdHash = JSON.parse('#{@player_ids}');
  let pageType = 'new_game';
  let default_team_a_avatar = '#{default_team_a_avatar}';
  let default_team_b_avatar = '#{default_team_b_avatar}';

app/views/rooms/game_play.haml
%script{:src => "/javascript/webcam.js"}

=render "match_screen"

=form_tag room_game_end_path(id: @room.id) do
  .row.center=submit_tag "continue", name: 'continue', class: "sf transparent-bg", id: "continueButton"
  .row=submit_tag "quit", name: 'quit', class: "sf sf-quit transparent-bg"

:javascript 
  videoRecording = false;
  console.log("setting webcam");
  Webcam.set({
    width: 480,
    height: 320,
    image_format: 'jpeg',
    jpeg_quality: 90
  });
  Webcam.attach(".video");
  console.log("Webcam Set");
  $(".video").hide();
  $(".replay").hide();
  setTimeout(function(){game_ongoing()},1000);

  function game_ongoing(){
    if (($("#team_a_score").text() != "W") && ($("#team_b_score").text() != "W") && (videoRecording == false)){
        videoRecording = true;
        console.log("conditions met to startrecording ");
        take_video(game_ongoing);
    }
    console.log("exiting")
  }
  function take_video(callback) {
    console.log("start recording");
    videoRecording = true;
    var startScoreA = $("#team_a_score").text();
    var startScoreB = $("#team_b_score").text();
    var counter = 0;
    var id;
    var pictures = [];
    var replayEnd = 1;
    var replayCounter = 0;
    id = setInterval(function(){
      if (($("#team_a_score").text() == startScoreA) && ($("#team_b_score").text() == startScoreB)){
        if (Webcam.loaded){
          Webcam.snap(function(data_uri){
            pictures[counter%250] = data_uri;
            counter++;
          });
        }
        else{
          clearInterval(id);
        }
        if (counter >=250){
          replayEnd = counter%250; 
          replayCounter = (counter+1)%250;
        }
        else{
          replayEnd = counter;
          replayCounter = 0;
        }
      }
      else{
        $(".replay").show();
        $(".replay").css({"visibility":"visibile",
                         "background" : 'url('+pictures[replayCounter]+') no-repeat center',
                         "z-index": "1",
                         "position": "absolute"});
        replayCounter = (replayCounter+1)%250;
        if (replayCounter == replayEnd){
          console.log("end record/playback");
          $(".replay").hide();
          videoRecording = false;
          clearInterval(id);
          callback();
        }

      }
      // if(counter > 0){
      //   counter --;
      //   Webcam.snap(function(data_uri){
      //     pictures.push(data_uri);
      //   });
      // }

  // if((counter == 0) && (counter1 > 1)){
  //   counter1 --;
  //   console.log(counter1);
  //   $(".replay").show();
  //   $(".replay").css({"visibility":"visibile",
  //                    "background" : 'url('+pictures[400-counter1]+') no-repeat center',
  //                    "z-index": "1",
  //                    "position": "absolute"});
  // }


    }, 30);
  }

app/views/rooms/game_view.haml
=render "match_screen"

app/views/rooms/increment_score.haml
{}

app/views/rooms/index.html.haml
%h1 Listing rooms

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @rooms.each do |room|
      %tr
        %td= room.name
        %td= link_to 'Show', room
        %td= link_to 'Edit', edit_room_path(room)
        %td= link_to 'Destroy', room, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Room', new_room_path

app/views/rooms/interstitial.haml
:javascript
  var counter = 5;
  var id;
  id = setInterval(function() {
      counter--;
      if(counter <= 0) {
        window.location.href="/rooms/#{@id}/game/newfull";
        clearInterval(id);
      }
  }, 1000);

app/views/rooms/leaderboard.haml
%div.row
  %div.column.small-12
    %h1.street-fighter.sublabel.text-center
      Leaderboard
%div.row
  %div.column.small-9.small-centered
    %table
      %thead
        %tr
          %td
            %h4.street-fighter
              Rank
          %td
            %h4.street-fighter
              Player
          %td
            %h4.street-fighter
              Rating
          %td
            %h4.street-fighter
              Deviation
      %tbody
        - @player_ratings.each_with_index do |player_rating,index|
          - player = player_rating.player
          %tr
            %td
              %h5.street-fighter
                =index + 1
            %td
              %h5.street-fighter
                =link_to(player.name, "/reports/player/#{player.id}", {:class => 'link-label'})
            %td
              %h5.street-fighter
                =(player_rating.skill * 1000).floor
            %td
              %h5.street-fighter
                =player_rating.deviation

app/views/rooms/show.html.haml
%p#notice= notice

=render "match_screen"

= link_to 'Edit', edit_room_path(@room)
\|
= link_to 'Back', rooms_path