config/routes.rb
Rails.application.routes.draw do
  resources :season_stats
  resources :player_ratings
  get 'reports' => 'reports#index', as: :report_index
  get 'reports/leaderboard' => 'reports#leaderboard', as: :report_leaderboard
  get 'reports/player/:player_id' => 'reports#player', as: :player_report
  get 'reports/gameHistory/:game_id' => 'reports#game', as: :game_report
  get 'reports/historyTable/:player_id_1(/:player_id_2)' => 'reports#history', as: :history_table

  get 'players/:player_id/change_pin' => 'players#change_player_pin', as: :change_player_pin
  post 'players/:player_id/change_pin' => 'players#change_player_pin_post', as: :change_player_pin_post

  resources :rooms do
      resources :seasons do
        get 'leaderboard' => 'seasons#leaderboard', as: :leaderboard
      end
      get 'controller' => 'rooms#controller'
      get 'leaderboard' => 'rooms#leaderboard', as: :leaderboard
      get 'game/interstitial' => 'rooms#interstitial', as: :game_interstitial
      get 'game/new' => 'rooms#game_new', as: :game_new
      post 'game/new' => 'rooms#game_new_post', as: :game_new_post
      get 'game/' => 'rooms#game_view', as: :game_view
      get 'game/play' => 'rooms#game_play', as: :game_play
      post 'game/end' => 'rooms#game_end_post', as: :game_end
      get 'game/newfull' => 'rooms#game_newfull', as: :game_newfull
      post 'game/player_count' => 'rooms#game_player_count_post', as: :game_player_count_post
      get 'game/lookup_player' => 'players#lookup_player', as: :game_lookup_player
      get 'game/login_as/:player_id' => 'players#login_as_player', as: :game_login_as_player
      post 'game/login_as/:player_id' => 'players#login_as_player_post', as: :game_login_as_player_post

      post 'game/new/players/clear' => 'rooms#players_clear_post', as: :game_players_clear_post
      get 'game/new/players/create' => 'players#new', as: :game_new_player
      get 'game/new/players/create/cancel' => 'players#new_cancel', as: :game_new_player_cancel
      post 'game/new/players/create' => 'players#new_post', as: :game_new_player_post
      get 'game/new/players/:player_id' => 'players#confirm', as: :game_player_confirm
      delete 'game/new/players/:player_id' => 'players#delete', as: :game_player_delete
      get 'game/new/players/:player_id/attach_image' => 'players#attach_image', as: :game_player_attach_image
      post 'game/new/players/:player_id/attach_image' => 'players#attach_image_post', as: :game_player_attach_image_post
  end

  root 'rooms#home'
  
  get '/api/rooms/:id/end' => 'rooms#end_game'
  get '/api/rooms/:id/team/:team/increment/:request_id' => 'rooms#increment_score', as: :increment_score
  get '/api/rooms/:id/team/:team/decrement/:request_id' => 'rooms#decrement_score', as: :decrement_score
  get '/api/rooms/:id/team/:team/taunt/:request_id' => 'rooms#taunt', as: :taunt
  get '/api/rooms/:id/status' => 'rooms#room_status', as: :room_status
  get '/api/rooms/:room_id/players/add' => 'players#handle_player_hash', as: :handle_player_hash
  get '/api/rooms/:room_id/players/predict' => 'players#predict_game', as: :predict_game
  get '/api/rooms/:room_id/players/optimize' => 'players#optimize_teams', as: :optimize_teams
  get '/api/rooms/:room_id/players/rank' => 'players#get_rank', as: :get_player_rank
  get '/api/rooms/:room_id/send_current_scores' => 'rooms#send_current_scores'
  get '/api/rooms/:id/activeseason' => 'rooms#active_season'
  get '/api/players' => 'players#list_all_players'

  resources :bathrooms do
    get 'stalls/:stall_id/:state' => 'bathrooms#set_stall_status'
    get 'stalls_stats/:days_ago' => 'bathrooms#stats', as: :stall_stats
  end
end

app/models/season_stat.rb
class SeasonStat < ApplicationRecord
  belongs_to :player
  belongs_to :season
end

app/controllers/season_stats_controller.rb
class SeasonStatsController < ApplicationController
  before_action :set_season_stat, only: [:show, :edit, :update, :destroy]

  # GET /season_stats
  # GET /season_stats.json
  def index
    @season_stats = SeasonStat.all
  end

  # GET /season_stats/1
  # GET /season_stats/1.json
  def show
  end

  # GET /season_stats/new
  def new
    @season_stat = SeasonStat.new
  end

  # GET /season_stats/1/edit
  def edit
  end

  # POST /season_stats
  # POST /season_stats.json
  def create
    @season_stat = SeasonStat.new(season_stat_params)

    respond_to do |format|
      if @season_stat.save
        format.html { redirect_to @season_stat, notice: 'Season stat was successfully created.' }
        format.json { render :show, status: :created, location: @season_stat }
      else
        format.html { render :new }
        format.json { render json: @season_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /season_stats/1
  # PATCH/PUT /season_stats/1.json
  def update
    respond_to do |format|
      if @season_stat.update(season_stat_params)
        format.html { redirect_to @season_stat, notice: 'Season stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @season_stat }
      else
        format.html { render :edit }
        format.json { render json: @season_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /season_stats/1
  # DELETE /season_stats/1.json
  def destroy
    @season_stat.destroy
    respond_to do |format|
      format.html { redirect_to season_stats_url, notice: 'Season stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season_stat
      @season_stat = SeasonStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_stat_params
      params.require(:season_stat).permit(:player_id, :season_id, :has_completed_aggregation, :player_count, :wins, :losses, :most_defeated_player_id, :most_defeated_by_player_id, :average_win_margin, :average_loss_margin, :total_points_scored, :total_points_scored_against)
    end
end

app/helpers/season_stats_helper.rb
module SeasonStatsHelper
end

app/views/season_stats/_form.html.haml
= form_for @season_stat do |f|
  - if @season_stat.errors.any?
    #error_explanation
      %h2= "#{pluralize(@season_stat.errors.count, "error")} prohibited this season_stat from being saved:"
      %ul
        - @season_stat.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :player_id
    = f.number_field :player_id
  .field
    = f.label :season_id
    = f.number_field :season_id
  .field
    = f.label :has_completed_aggregation
    = f.check_box :has_completed_aggregation
  .field
    = f.label :player_count
    = f.number_field :player_count
  .field
    = f.label :wins
    = f.number_field :wins
  .field
    = f.label :losses
    = f.number_field :losses
  .field
    = f.label :most_defeated_player_id
    = f.number_field :most_defeated_player_id
  .field
    = f.label :most_defeated_by_player_id
    = f.number_field :most_defeated_by_player_id
  .field
    = f.label :average_win_margin
    = f.text_field :average_win_margin
  .field
    = f.label :average_loss_margin
    = f.text_field :average_loss_margin
  .field
    = f.label :total_points_scored
    = f.number_field :total_points_scored
  .field
    = f.label :total_points_scored_against
    = f.number_field :total_points_scored_against
  .actions
    = f.submit 'Save'

app/views/season_stats/edit.html.haml
%h1 Editing season_stat

= render 'form'

= link_to 'Show', @season_stat
\|
= link_to 'Back', season_stats_path

app/views/season_stats/index.html.haml
%h1 Listing season_stats

%table
  %thead
    %tr
      %th Player
      %th Season
      %th Has completed aggregation
      %th Player count
      %th Wins
      %th Losses
      %th Most defeated player
      %th Most defeated by player
      %th Average win margin
      %th Average loss margin
      %th Total points scored
      %th Total points scored against
      %th
      %th
      %th

  %tbody
    - @season_stats.each do |season_stat|
      %tr
        %td= season_stat.player_id
        %td= season_stat.season_id
        %td= season_stat.has_completed_aggregation
        %td= season_stat.player_count
        %td= season_stat.wins
        %td= season_stat.losses
        %td= season_stat.most_defeated_player_id
        %td= season_stat.most_defeated_by_player_id
        %td= season_stat.average_win_margin
        %td= season_stat.average_loss_margin
        %td= season_stat.total_points_scored
        %td= season_stat.total_points_scored_against
        %td= link_to 'Show', season_stat
        %td= link_to 'Edit', edit_season_stat_path(season_stat)
        %td= link_to 'Destroy', season_stat, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Season stat', new_season_stat_path

app/views/season_stats/new.html.haml
%h1 New season_stat

= render 'form'

= link_to 'Back', season_stats_path

app/views/season_stats/show.html.haml
%p#notice= notice

%p
  %b Player:
  = @season_stat.player_id
%p
  %b Season:
  = @season_stat.season_id
%p
  %b Has completed aggregation:
  = @season_stat.has_completed_aggregation
%p
  %b Player count:
  = @season_stat.player_count
%p
  %b Wins:
  = @season_stat.wins
%p
  %b Losses:
  = @season_stat.losses
%p
  %b Most defeated player:
  = @season_stat.most_defeated_player_id
%p
  %b Most defeated by player:
  = @season_stat.most_defeated_by_player_id
%p
  %b Average win margin:
  = @season_stat.average_win_margin
%p
  %b Average loss margin:
  = @season_stat.average_loss_margin
%p
  %b Total points scored:
  = @season_stat.total_points_scored
%p
  %b Total points scored against:
  = @season_stat.total_points_scored_against

= link_to 'Edit', edit_season_stat_path(@season_stat)
\|
= link_to 'Back', season_stats_path